let AdminManageMenus = {
  name: "Manage",
  accessLevel: "D",
  entities: [
    {
      name: "Areas",
      singularName: "Area",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      isReady: true,
      accessLevel: "A",
    },
    {
      name: "Customers",
      singularName: "Customer",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      isReady: true,
      dbCollection: "users",
      accessLevel: "A",
    },
    {
      name: "DailyEntries",
      singularName: "DailyEntry",
      addFacility: false,
      deleteFacility: false,
      editFacility: false,
      isReady: true,
      dbCollection: "entries",
      accessLevel: "A",
    },
    {
      name: "Payments",
      singularName: "Payment",
      addFacility: false,
      deleteFacility: true,
      editFacility: true,
      isReady: true,
      dbCollection: "payments",
      accessLevel: "A",
    },
    {
      name: "Bills",
      singularName: "Bill",
      addFacility: true,
      deleteFacility: false,
      editFacility: false,
      isReady: true,
      dbCollection: "bills",
      accessLevel: "A",
    },
  ],
};
export default AdminManageMenus;
